[package]
name = "x3dh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "2.1.1"
hex-literal = "0.4.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"]}
